### ISSUE TITLE
Just out of curiosity: Why choose a code style inconsistent with Haxe?

### ISSUE THREAD

**Issue by kevinresol** [underscorediscovery/snow#64]
Haxe uses camel cases for var and functions and snow use small letters with underscore. Actually this makes me a little bit uneasy when coding. :sob:

**Comment by underscorediscovery** [comment]
Same type of reasons they chose camelCase, most likely. 

In the end, it doesn't _really_ impact anything except one's own perception.
Since I'd rather spend my time working than debating personal views on semantics - 
I won't say much more than this, here is my own perspective you're free to disagree with:

The mere suggestion that ALL code written in programming language X must conform to the original development team and their choices regarding naming, _is just absurd_ to me. The notion erases me as a human programmer, removes my countless years of history, understanding, habits and reasoning for choosing my own particular style just because I showed up? Count me out!

They/it doesn't have the right to any of that, unless given. For example, if contributing toward haxe or libraries with an existing format - I will whole heartedly abide by the best fit for the project.

In the same vein, third party users don't have the right to demand the haxe core team switch to snake case, because its immeasurably "better", and camelCase makes them uneasy. Programming just doesn't work that way :)

One of the things I love about coding is the personal nature of it - You probably wouldn't post this if that wasn't the case, so I appreciate the opinion/post.

Give and take, make stuff, and have fun! Don't let nonquantifiable details distract you from your goals.
