### ISSUE TITLE
web; load an image from an url throws error

### ISSUE THREAD

**Issue by smvilar** [underscorediscovery/snow#84]
I'm trying to use [this sample](https://gist.github.com/bmfs/18caf119cfc6bfeff5fd) from `awesome-snowkit` to load an image from the url and display it in a luxe texture.

I made this repo with the actual test: https://github.com/smvilar/luxe-image-from-url

The console displays this error when calling `Luxe.snow.assets.image_from_bytes`

```
error(failed to load image from bytes, on error: [object Event])
```

**Comment by smvilar** [comment]
@underscorediscovery have you seen this issue? I wanna know if I'm doing something wrong here.

**Comment by underscorediscovery** [comment]
I have seen this but I've been busy in the backend, but I had a quick look so long.

- I assumed the error message from browser would say something at all, it doesn't. So the log isn't helpful but it's actually all the browsers will tell, which is silly of them. I'll clarify the error on our side as much as I can.

- When I put looked in the debugger - it appears that your input data is actually invalid before being passed in, rather than an internal error. 

Here's what I mean, this is a working png file (default font):
![screen 2015-11-30 at 6 12 34 pm](https://cloud.githubusercontent.com/assets/236374/11485569/85e21b74-978e-11e5-884b-2ab22540c992.png)

And here is your data:
![screen 2015-11-30 at 6 12 53 pm](https://cloud.githubusercontent.com/assets/236374/11485574/8bd97464-978e-11e5-98f5-5d0017d9a533.png)

What you see here is actually a `�`, a replacement character.
When encoded as UTF-8, this character (`0xFFFD`) becomes `ï¿½` (`0xEF 0xBF 0xBD`).

When I see that - I know that somewhere, the data has been converted to UTF-8 encoding, when it shouldn't be. This means that it will mess with the raw PNG data, making the image data invalid.

In simpler words: The error comes from the conversions, before getting to the `image_from_bytes` call.

Internally snow [uses](https://github.com/underscorediscovery/snow/blob/master/snow/core/web/io/IO.hx#L42) `js.html.XMLHttpRequest()` directly, 
- it sets `request.overrideMimeType('text/plain; charset=x-user-defined');`
  - so that it doesn't get encoded by the server or browser
- sets async true (required) for `request.responseType = js.html.XMLHttpRequestResponseType.ARRAYBUFFER;`
- onload does `new Uint8Array(request.response)` because it's already a typed array

The reason I did it this way internally was because of similar encoding problems, where it must remain binary data in order to be used correctly.

Hope that helps so long.

**Comment by smvilar** [comment]
Thanks! I [updated](https://github.com/smvilar/luxe-image-from-url/commit/ca83d647a23d9928885b08b938726db051cff11e) the example to use `js.html.XMLHttpRequest` directly with the parameters you set and it worked.

I should warn @bmfs to update his gist

**Comment by anissen** [comment]
> I should warn @bmfs to update his gist

@smvilar Good idea. If you cannot reach him, you can fork his gist and correct it and then ping me and I'll point the link to the corrected gist instead.

**Comment by bmfs** [comment]
just updated the gist to use Luxe.snow.io.data_load(url).

Thanks for the warning

**Comment by underscorediscovery** [comment]
:+1:
