### ISSUE TITLE
Platform-specific limitations?

### ISSUE THREAD

**Issue by ashes999** [underscorediscovery/snow#92]
I'm in the middle of writing a project in HaxeFlixel. I just discovered that their `audio.pitch` doesn't work on Flash and HTML5.

How does Snow (and conversely, luxe, which uses the audio classes directly) handle audio? Are there any features that don't work on Flash or HTML5, or any other platforms?

Also, I didn't see any mention in any of the documentation. Are there any features or functionality that don't span all platforms?

**Comment by underscorediscovery** [comment]
snow doesn't support flash.

All endpoints in the snow api's that aren't on the _module_ level have parity across targets. That means native (android, ios, linux, mac, windows) and web (webgl) have parity for all the audio endpoints. The module distinction means that modules (like OpenAL, or maybe native file access) can still provide access to features that break compatibility, but the distinction is clear that the user must be wary.

So, there are features that don't span for the sake of access, but the snow api itself on the top level is.

A simple audio test [can be played with here](https://dl.dropboxusercontent.com/u/736396/luxe/tests/audio/index.html). 

As far as details goes, on native (currently) OpenAL is used on all targets by default, and on web the Web Audio API is used for all but streaming audio, in which case an `<audio>` tag is used due to the fact you can't stream anything yet on Web Audio without loading the entire file first (which defeats the point of streaming in most cases).

Does that help?

**Comment by ashes999** [comment]
Yes, that helps a lot, thanks.
